Version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/android:api-27-alpha
      
    steps:
      - checkout
      - run: echo "hello"
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Chmod permissions
          command: |
                   sudo chmod +x ./gradlew
                   ./gradlew dependencies
          #- ANDROID_HOME=/usr/local/android-sdk-linux ./gradlew dependencies
      - store_artifacts:
          path: app/build/reports
          destination: reports
