Version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-25-alpha
      
    steps:
      - checkout
      - run: echo "hello"
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
