Version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m  
    steps:
      - checkout
      - run: echo "hello"
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Chmod permissions and Build
          command: |
                   sudo chmod +x ./gradlew
                   ./gradlew dependencies
          #- ANDROID_HOME=/usr/local/android-sdk-linux ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Lists installed targets
          command: android list target
          environment:
          TERM: dumb
      - run:
          name: Show list of system-images
          command: sdkmanager --list --verbose | grep system-images
      - run:
          name: Accept licenses
          command: yes | sdkmanager --licenses || true
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-25;google_apis;armeabi-v7a" && echo "no" | avdmanager create avd -n emulatorTest -k "system-images;android-25;google_apis;armeabi-v7a"
      
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator -avd emulatorTest -noaudio -no-boot-anim -no-window -no-accel -memory 2048 -verbose &
          background: true

      - run:
          name: Run Espresso UI Tests
          command: ./gradlew test
      - store_artifacts:
          path: app/build/reports
          destination: reports
