Version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-25-alpha
      
    steps:
      - checkout
      - run: echo "hello"
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
          - ANDROID_HOME=/usr/local/android-sdk-linux ./gradlew dependencies
      - run:
          name: Download Dependencies
          command: ./gradllew androidDependencies
